insert into university ( id, name, name_upper_case ) values ( 1,  'Massachusetts Institute of Technology','MASSACHUSETTS INSTITUTE OF TECHNOLOGY');
insert into university ( id, name, name_upper_case ) values ( 2,  'Harvard University', 'HARVARD UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 3,  'Boston University', 'BOSTON UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 4,  'Tufts University', 'TUFTS UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 5,  'University of Massachusetts Amherst','UNIVERSITY OF MASSACHUSETTS AMHERST');
insert into university ( id, name, name_upper_case ) values ( 6,  'Boston College','BOSTON COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 7,  'Northeastern University','NORTHEASTERN UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 8,  'Brandeis University', 'BRANDEIS UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 9,  'Worcester Polytechnic Institute','WORCESTER POLYTECHNIC INSTITUTE');
insert into university ( id, name, name_upper_case ) values ( 10, 'Berklee College of Music','BERKLEE COLLEGE OF MUSIC');
insert into university ( id, name, name_upper_case ) values ( 11, 'University of Massachusetts Boston','UNIVERSITY OF MASSACHUSETTS BOSTON');
insert into university ( id, name, name_upper_case ) values ( 12, 'University of Massachusetts Lowell','UNIVERSITY OF MASSACHUSETTS LOWELL');
insert into university ( id, name, name_upper_case ) values ( 13, 'Mount Holyoke College','MOUNT HOLYOKE COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 14, 'Amherst College','AMHERST COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 15, 'Smith College','SMITH COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 16, 'Williams College','WILLIAMS COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 17, 'Clark University','CLARK UNIVERSITY');
insert into university ( id, name, name_upper_case ) values ( 18, 'University of Massachusetts Medical School','UNIVERSITY OF MASSACHUSETTS MEDICAL SCHOOL');
insert into university ( id, name, name_upper_case ) values ( 19, 'Wellesley College','WELLESLEY COLLEGE');
insert into university ( id, name, name_upper_case ) values ( 20, 'Babson College','BABSON COLLEGE');

insert into course ( id, school_id, name, name_lower_case ) values ( 1,  1, 'Principles of Microeconomics','principles of microeconomics');
insert into course ( id, school_id, name, name_lower_case ) values ( 2,  1, 'Principles of Macroeconomics','principles of macroeconomics');
insert into course ( id, school_id, name, name_lower_case ) values ( 3,  1, 'Intermediate Macroeconomics','intermediate macroeconomics');
insert into course ( id, school_id, name, name_lower_case ) values ( 4,  1, 'Advanced Macroeconomics','advanced macroeconomics');
insert into course ( id, school_id, name, name_lower_case ) values ( 5,  1, 'Microeconomic Theory I','microeconomic theory i');
insert into course ( id, school_id, name, name_lower_case ) values ( 6,  1, 'Microeconomic Theory II','microeconomic theory ii');
insert into course ( id, school_id, name, name_lower_case ) values ( 7,  1, 'Microeconomic Theory III','microeconomic theory iii');
insert into course ( id, school_id, name, name_lower_case ) values ( 8,  1, 'Microeconomic Theory IV','microeconomic theory iv');
insert into course ( id, school_id, name, name_lower_case ) values ( 9,  1, 'Physics I','physics i');
insert into course ( id, school_id, name, name_lower_case ) values ( 10, 1, 'Physics II','physics ii');
insert into course ( id, school_id, name, name_lower_case ) values ( 11, 1, 'Physics III','physics iii');
insert into course ( id, school_id, name, name_lower_case ) values ( 12, 1, 'Quantum Physics I','quantum physics i');
insert into course ( id, school_id, name, name_lower_case ) values ( 13, 2, 'Computational Physics','computational physics');
insert into course ( id, school_id, name, name_lower_case ) values ( 14, 2, 'Computational Fluid Dynamics','computational fluid dynamics');
insert into course ( id, school_id, name, name_lower_case ) values ( 15, 11, 'CHEM 115','chem 115');
insert into course ( id, school_id, name, name_lower_case ) values ( 16, 11, 'CHEM 116','chem 116');
insert into course ( id, school_id, name, name_lower_case ) values ( 17, 11, 'CHEM 117','chem 117');
insert into course ( id, school_id, name, name_lower_case ) values ( 18, 11, 'CHEM 118','chem 118');
insert into course ( id, school_id, name, name_lower_case ) values ( 19, 11, 'ECON 101','econ 101');
insert into course ( id, school_id, name, name_lower_case ) values ( 20, 11, 'ECON 102','econ 102');
insert into course ( id, school_id, name, name_lower_case ) values ( 21, 11, 'BIOL 518','biol 518');
insert into course ( id, school_id, name, name_lower_case ) values ( 22, 11, 'BIOL 519','biol 519');
insert into course ( id, school_id, name, name_lower_case ) values ( 23, 11, 'BIOL 529','biol 529');
insert into course ( id, school_id, name, name_lower_case ) values ( 24, 11, 'BIOL 699','biol 699');
insert into course ( id, school_id, name, name_lower_case ) values ( 25, 11, 'BIOL 899','biol 899');
insert into course ( id, school_id, name, name_lower_case ) values ( 26, 11, 'CS 110','cs 110');
insert into course ( id, school_id, name, name_lower_case ) values ( 27, 11, 'CS 210','cs 210');
insert into course ( id, school_id, name, name_lower_case ) values ( 28, 11, 'CS 310','cs 310');
insert into course ( id, school_id, name, name_lower_case ) values ( 29, 11, 'CS 410','cs 410');
insert into course ( id, school_id, name, name_lower_case ) values ( 30, 11, 'CS 420','cs 420');
insert into course ( id, school_id, name, name_lower_case ) values ( 31, 11, 'CS 430','cs 430');
